[package]
name = "x-46ki75-notification-lib"
version = "0.1.0"
edition = "2024"
authors = ["Chomolungma Shirayuki"]

[dependencies]
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
